In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)

print("Libraries Loaded Successfully")

Libraries Loaded Successfully

In [3]:
df = pd.read_csv("data/customer_segmentation.csv")

df.head()

,Customer ID,Age,Gender,Marital Status,Education Level,Geographic Information,Occupation,Income Level,Behavioral Data,Purchase History,Interactions with Customer Service,Insurance Products Owned,Coverage Amount,Premium Amount,Policy Type,Customer Preferences,Preferred Communication Channel,Preferred Contact Time,Preferred Language,Segmentation Group
0,84966,23,Female,Married,Associate Degree,Mizoram,Entrepreneur,70541,policy5,04-10-2018,Phone,policy2,366603,2749,Group,Email,In-Person Meeting,Afternoon,English,Segment5
1,95568,26,Male,Widowed,Doctorate,Goa,Manager,54168,policy5,11-06-2018,Chat,policy1,780236,1966,Group,Mail,In-Person Meeting,Morning,French,Segment5
2,10544,29,Female,Single,Associate Degree,Rajasthan,Entrepreneur,73899,policy5,06-05-2021,Email,policy3,773926,4413,Group,Email,Mail,Evening,German,Segment3
3,77033,20,Male,Divorced,Bachelor's Degree,Sikkim,Entrepreneur,63381,policy5,09-02-2018,Chat,policy2,787815,4342,Family,Text,In-Person Meeting,Anytime,French,Segment3
4,88160,25,Female,Separated,Bachelor's Degree,West Bengal,Manager,38794,policy1,09-10-2018,Chat,policy4,366506,1276,Family,Email,Text,Weekends,English,Segment2

In [4]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

df.shape

Rows: 53503
Columns: 20

(53503, 20)

In [5]:
df.columns.tolist()

['Customer ID',
 'Age',
 'Gender',
 'Marital Status',
 'Education Level',
 'Geographic Information',
 'Occupation',
 'Income Level',
 'Behavioral Data',
 'Purchase History',
 'Interactions with Customer Service',
 'Insurance Products Owned',
 'Coverage Amount',
 'Premium Amount',
 'Policy Type',
 'Customer Preferences',
 'Preferred Communication Channel',
 'Preferred Contact Time',
 'Preferred Language',
 'Segmentation Group']

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53503 entries, 0 to 53502
Data columns (total 20 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Customer ID                         53503 non-null  int64
 1   Age                                 53503 non-null  int64
 2   Gender                              53503 non-null  object
 3   Marital Status                      53503 non-null  object
 4   Education Level                     53503 non-null  object
 5   Geographic Information              53503 non-null  object
 6   Occupation                          53503 non-null  object
 7   Income Level                        53503 non-null  int64
 8   Behavioral Data                     53503 non-null  object
 9   Purchase History                    53503 non-null  object
 10  Interactions with Customer Service  53503 non-null  object
 11  Insurance Products Owned            53503 non-null  object
 12  Coverage Amount                     53503 non-null  int64
 13  Premium Amount                      53503 non-null  int64
 14  Policy Type                         53503 non-null  object
 15  Customer Preferences                53503 non-null  object
 16  Preferred Communication Channel     53503 non-null  object
 17  Preferred Contact Time              53503 non-null  object
 18  Preferred Language                  53503 non-null  object
 19  Segmentation Group                  53503 non-null  object
dtypes: int64(5), object(15)
memory usage: 8.2+ MB

In [7]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Customer ID,53503.0,52265.204998,28165.000067,1.0,28950.5,55858.0,76096.0,100000.0
Age,53503.0,44.140945,15.079486,18.0,32.0,43.0,57.0,70.0
Income Level,53503.0,82768.324318,36651.075670,20001.0,51568.5,80719.0,115973.5,149999.0
Coverage Amount,53503.0,492580.789638,268405.505571,50001.0,249613.5,477261.0,739124.0,1000000.0
Premium Amount,53503.0,3023.702447,1285.834295,500.0,1817.0,3194.0,4311.5,5000.0

In [8]:
missing = pd.DataFrame({
    "Missing Count": df.isnull().sum(),
    "Missing Percentage": round(df.isnull().mean()*100,2)
})

missing

                                    Missing Count  Missing Percentage
Customer ID                                     0                 0.0
Age                                             0                 0.0
Gender                                          0                 0.0
Marital Status                                  0                 0.0
Education Level                                 0                 0.0
Geographic Information                          0                 0.0
Occupation                                      0                 0.0
Income Level                                    0                 0.0
Behavioral Data                                 0                 0.0
Purchase History                                0                 0.0
Interactions with Customer Service              0                 0.0
Insurance Products Owned                        0                 0.0
Coverage Amount                                 0                 0.0
Premium Amount                                  0                 0.0
Policy Type                                     0                 0.0
Customer Preferences                            0                 0.0
Preferred Communication Channel                 0                 0.0
Preferred Contact Time                          0                 0.0
Preferred Language                              0                 0.0
Segmentation Group                              0                 0.0

In [9]:
duplicates = df.duplicated().sum()

print("Duplicate Rows:", duplicates)

Duplicate Rows: 0

In [10]:
for col in df.columns:
    print("\n", col)
    print(df[col].nunique())

 Customer ID
40259

 Age
53

 Gender
2

 Marital Status
5

 Education Level
5

 Geographic Information
35

 Occupation
9

 Income Level
42779

 Behavioral Data
5

 Purchase History
2016

 Interactions with Customer Service
5

 Insurance Products Owned
5

 Coverage Amount
51765

 Premium Amount
4460

 Policy Type
4

 Customer Preferences
5

 Preferred Communication Channel
5

 Preferred Contact Time
5

 Preferred Language
5

 Segmentation Group
5

In [11]:
summary = pd.DataFrame({
    "Data Type": df.dtypes,
    "Missing": df.isnull().sum(),
    "Unique": df.nunique()
})

summary

                                   Data Type  Missing  Unique
Customer ID                            int64        0   40259
Age                                    int64        0      53
Gender                                object        0       2
Marital Status                        object        0       5
Education Level                       object        0       5
Geographic Information                object        0      35
Occupation                            object        0       9
Income Level                           int64        0   42779
Behavioral Data                       object        0       5
Purchase History                      object        0    2016
Interactions with Customer Service    object        0       5
Insurance Products Owned              object        0       5
Coverage Amount                        int64        0   51765
Premium Amount                         int64        0    4460
Policy Type                           object        0       4
Customer Preferences                  object        0       5
Preferred Communication Channel       object        0       5
Preferred Contact Time                object        0       5
Preferred Language                    object        0       5
Segmentation Group                    object        0       5

In [12]:
#1. Dataset contains customer demographic information.

#2. No major missing values.

#3. Dataset suitable for clustering.

#4. Numerical features available for segmentation.

#5. Data quality is good.